### PR TITLE
dragonberry

### PR DESCRIPTION
**Pull request by faddat**
https://github.com/cosmos/cosmos-sdk/releases/tag/v0.46.6

### CODE REVIEW

**Comment by sascha1337** [comment]
thanks m8 - any chance 2 drop a hint, why swagger and grpcui do not work ?

```bash
joe@joerver:~$ grpcui -plaintext localhost:9090
Failed to compute set of methods to expose: Symbol not found: cosmos.staking.v1beta1.Query
```

**Comment by faddat** [comment]
sdk 46 sir. 

hmmm actually -- may have more to do with the liquidity staking module. 

It has a differently named set of .proto files

**Comment by sascha1337** [comment]
i smelled it - need to dive more into the golang sdk side s00n

**Comment by reecepbcups** [comment]
@sascha1337 yea liquid staking is used instead of standard staking proto. Same issue as you get frontend like you've seen

Pupmos solved & has the tooling built I think for it

**Pull request merged**
